version: '3.8'

services:
  proxy:
    build: ./docker/nginx
    ports: 
      - 1337:80
    depends_on: 
      - web
  web:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
      target: production
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
