version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=homedjango
      - POSTGRES_PASSWORD=homedjango
      - POSTGRES_DB=homedjango_dev

volumes:
  postgres_data:
